### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Nugine** [Nugine/rust-utils#1]
+ [ ] split justfile
+ [ ] refactor CI

### nugine-rust-utils
+ [ ] `Vec::drain_filter_`
+ [ ] `slice::sort_by_key_`

### cst-locks
status: broken
+ [ ] fix miri tests
